version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13
    env_file: .env.example
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: andreysmart/kittygram_backend
    env_file: .env.example
    depends_on:
      - db
    volumes:
      - static_volume:/backend_static/
      - media_volume:/media/

  frontend:
    image: andreysmart/kittygram_frontend
    env_file: .env.example
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static/

  gateway:
    image: andreysmart/kittygram_gateway
    env_file: .env.example
    ports:
      - 9000:80
    volumes:
      - static_volume:/staticfiles/
      - media_volume:/media/
